version: '3.8'

services:

  # Redis Service (Message Broker)
  redis:
    image: redis:alpine
    container_name: nexus_redis
    ports:
      - "6379:6379"
    networks:
      - ai-voice-network
    restart: always
  # -------
  # Service : Core API (Backend)
  # -------
  backend:
    build:
      context: ./services/core-api
      dockerfile: Dockerfile
    container_name: ai_voice_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./services/core-api:/app
    ports:
      - "8000:8000"
    env_file:
      - ./services/core-api/.env
    environment:
      - DB_HOST=ai_voice_db_psql
      - DB_NAME=${DB_NAME:-ai_voice_db}
      - DB_USER=${DB_USER:-ai_voice_user}
      - DB_PASSWORD=${DB_PASSWORD:-ai_voice_password}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - ai-voice-network

  # -------
  # Service 2: Frontend
  # --------
  frontend:
    build:
      context: ./voice-frontend
      dockerfile: Dockerfile
    container_name: ai_voice_frontend
    volumes:
      - ./voice-frontend/src:/app/src
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend
    networks:
      - ai-voice-network

  # ------
  # Service 3: Database
  # -------
  db:
    image: postgres:15-alpine
    container_name: ai_voice_db_psql
    volumes:
      - ai-voice-db-data:/var/lib/postgresql/data
    env_file:
      - ./services/core-api/.env
    environment:
      - POSTGRES_DB=${DB_NAME:-ai_voice_db}
      - POSTGRES_USER=${DB_USER:-ai_voice_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-ai_voice_password}
    ports:
      - "5432:5432"
    networks:
      - ai-voice-network

  # ------
  # Service 4: AI Agent (The Brain) 🧠
  # -------
  ai_agent:
    build:
      context: ./services/ai-worker
      dockerfile: Dockerfile
    container_name: ai_voice_agent
    volumes:
      - ./services/ai-worker:/app
    env_file:
      - ./services/ai-worker/.env
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - ai-voice-network



  # ✅ 2. New FastAPI Service
  realtime-api:
    build:
      context: ./services/realtime-api
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    container_name: ai_voice_realtime
    ports:
      - "8002:8002"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - redis
    networks:
      - ai-voice-network
# -------
# Networks & Volumes Definition
# -------
networks:
  ai-voice-network:
    driver: bridge

volumes:
  ai-voice-db-data:
