import uuid
from django.db import models
from django.conf import settings
from django.utils.text import slugify


class Project(models.Model):
    # ---------------------------------------------------------
    # 1. Enums (Standardizing Data for AI parsing)
    # ---------------------------------------------------------
    class Status(models.TextChoices):
        DRAFT = 'DRAFT', 'Draft'
        PLANNING = 'PLANNING', 'Planning'
        ACTIVE = 'ACTIVE', 'Active'
        ON_HOLD = 'ON_HOLD', 'On Hold'
        COMPLETED = 'COMPLETED', 'Completed'
        CANCELLED = 'CANCELLED', 'Cancelled'

    class Priority(models.TextChoices):
        LOW = 'LOW', 'Low'
        MEDIUM = 'MEDIUM', 'Medium'
        HIGH = 'HIGH', 'High'
        CRITICAL = 'CRITICAL', 'Critical'

    class RiskLevel(models.TextChoices):
        SAFE = 'SAFE', 'Safe (On Track)'
        AT_RISK = 'AT_RISK', 'At Risk (Minor Issues)'
        OFF_TRACK = 'OFF_TRACK', 'Off Track (Critical Issues)'

    # ---------------------------------------------------------
    # 2. Identifiers & Core Info
    # ---------------------------------------------------------
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True, blank=True,
                            help_text="Used for clean URLs (e.g., /projects/mars-colony)")
    description = models.TextField(blank=True, help_text="Detailed project scope and objectives.")

    # ---------------------------------------------------------
    # 3. The Nexus Layer (AI & Analytics) 🧠
    # ---------------------------------------------------------
    # The AI can write a summarized status report here autonomously
    ai_summary = models.TextField(blank=True, help_text="Autogenerated summary by Nexus AI based on recent activity.")

    # Calculated progress (0-100%)
    completion_percentage = models.PositiveIntegerField(default=0)

    # AI or Manager can flag the project risk
    risk_level = models.CharField(max_length=20, choices=RiskLevel.choices, default=RiskLevel.SAFE)

    # Flexible tags for categorization (e.g., ["Frontend", "AI", "Q3"])
    tags = models.JSONField(default=list, blank=True, help_text="List of tags for filtering and AI context.")

    # ---------------------------------------------------------
    # 4. Tracking & Classification
    # ---------------------------------------------------------
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.PLANNING)
    priority = models.CharField(max_length=20, choices=Priority.choices, default=Priority.MEDIUM)

    # ---------------------------------------------------------
    # 5. Financials & Resources (For ROI Analysis)
    # ---------------------------------------------------------
    allocated_budget = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    spent_budget = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    estimated_hours = models.PositiveIntegerField(null=True, blank=True)

    # ---------------------------------------------------------
    # 6. Relationships (The Team Structure)
    # ---------------------------------------------------------
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name='owned_projects',
        help_text="The ultimate stakeholder or sponsor."
    )
    manager = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name='managed_projects',
        help_text="The day-to-day project manager."
    )
    team = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='assigned_projects',
        blank=True
    )

    # ---------------------------------------------------------
    # 7. Timeline & Lifecycle
    # ---------------------------------------------------------
    start_date = models.DateField(null=True, blank=True)
    target_end_date = models.DateField(null=True, blank=True)
    actual_end_date = models.DateField(null=True, blank=True)

    # ---------------------------------------------------------
    # 8. Audit & Soft Deletion (Enterprise Standard)
    # ---------------------------------------------------------
    is_archived = models.BooleanField(default=False, help_text="Soft delete: Hides project without deleting data.")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = "Project"
        verbose_name_plural = "Projects"

    def __str__(self):
        return f"{self.name} ({self.get_status_display()})"

    def save(self, *args, **kwargs):
        # Auto-generate slug from name if not provided
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)